"""
PlatformIO pre-script: build the React web app and embed it as src/web_bundle.h.

Skips the npm build if src/web_bundle.h is newer than all source files under
web/ (excluding node_modules and dist).  Always re-embeds after a rebuild.
"""
Import("env")
import gzip
import os
import subprocess
import sys

REPO_ROOT    = env.subst("$PROJECT_DIR")
WEB_DIR      = os.path.join(REPO_ROOT, "web")
DIST_FILE    = os.path.join(WEB_DIR, "dist", "index.html")
BUNDLE_H     = os.path.join(REPO_ROOT, "src", "web_bundle.h")

# On Windows npm is a .cmd script, not an exe — find it explicitly.
def _find_npm():
    for candidate in ["npm.cmd", "npm"]:
        for path_dir in os.environ.get("PATH", "").split(os.pathsep):
            full = os.path.join(path_dir, candidate)
            if os.path.isfile(full):
                return full
    return "npm"  # fallback, let the OS resolve it

NPM = _find_npm()


def _newest_mtime(directory):
    newest = 0
    extensions = (".html", ".jsx", ".js", ".ts", ".tsx", ".css", ".json")
    for root, dirs, files in os.walk(directory):
        # skip generated/installed dirs
        dirs[:] = [d for d in dirs if d not in ("node_modules", "dist", ".vite")]
        for f in files:
            if any(f.endswith(e) for e in extensions):
                mtime = os.path.getmtime(os.path.join(root, f))
                if mtime > newest:
                    newest = mtime
    return newest


def _bundle_is_fresh():
    if not os.path.exists(BUNDLE_H):
        return False
    return _newest_mtime(WEB_DIR) <= os.path.getmtime(BUNDLE_H)


def _embed():
    with open(DIST_FILE, "rb") as f:
        raw = f.read()

    compressed = gzip.compress(raw, compresslevel=9)
    raw_kb  = len(raw) / 1024
    comp_kb = len(compressed) / 1024
    ratio   = 100 * (1 - len(compressed) / len(raw))
    print(f"web bundle: {raw_kb:.1f} KB -> {comp_kb:.1f} KB gzipped ({ratio:.0f}% reduction)")

    chunks = [compressed[i:i+12] for i in range(0, len(compressed), 12)]
    lines  = ["    " + ", ".join(f"0x{b:02x}" for b in chunk) for chunk in chunks]

    header = (
        "/* Auto-generated by pre_web_bundle.py - do not edit */\n"
        f"/* Source: web/dist/index.html | raw {raw_kb:.1f} KB -> gzip {comp_kb:.1f} KB */\n"
        "#pragma once\n"
        "#include <stddef.h>\n"
        "\n"
        "static const unsigned char WEB_BUNDLE_GZ[] = {\n"
        + ",\n".join(lines) + "\n"
        "};\n"
        "\n"
        f"static const size_t WEB_BUNDLE_GZ_LEN = {len(compressed)}U;\n"
    )

    with open(BUNDLE_H, "w", encoding="utf-8") as f:
        f.write(header)
    print(f"web bundle: written {BUNDLE_H} ({len(compressed)} bytes)")


if _bundle_is_fresh():
    print("web bundle: up to date, skipping npm build")
else:
    print("web bundle: rebuilding …")
    subprocess.check_call([NPM, "install", "--prefer-offline"], cwd=WEB_DIR)
    subprocess.check_call([NPM, "run", "build"], cwd=WEB_DIR)
    _embed()
