#!/usr/bin/env python3
"""
embed_web.py — converts web/dist/index.html into src/web_bundle.h

Usage (run from repo root):
    python scripts/embed_web.py

Output: src/web_bundle.h
  - WEB_BUNDLE_GZ[]     : gzipped HTML+JS as a C byte array
  - WEB_BUNDLE_GZ_LEN   : length in bytes

web_server.c serves this with Content-Encoding: gzip.
"""

import gzip
import os
import sys

DIST_FILE   = os.path.join('web', 'dist', 'index.html')
OUTPUT_FILE = os.path.join('src', 'web_bundle.h')


def main():
    if not os.path.exists(DIST_FILE):
        print(f'ERROR: {DIST_FILE} not found. Run "cd web && npm run build" first.',
              file=sys.stderr)
        sys.exit(1)

    with open(DIST_FILE, 'rb') as f:
        raw = f.read()

    compressed = gzip.compress(raw, compresslevel=9)

    raw_kb  = len(raw)  / 1024
    comp_kb = len(compressed) / 1024
    ratio   = 100 * (1 - len(compressed) / len(raw))
    print(f'web bundle: {raw_kb:.1f} KB → {comp_kb:.1f} KB gzipped ({ratio:.0f}% reduction)')

    # Format as C byte array
    hex_bytes = ', '.join(f'0x{b:02x}' for b in compressed)
    # Wrap at 80 chars / 12 bytes per line for readability
    chunks = [compressed[i:i+12] for i in range(0, len(compressed), 12)]
    lines  = ['    ' + ', '.join(f'0x{b:02x}' for b in chunk) for chunk in chunks]
    hex_block = ',\n'.join(lines)

    header = f"""\
/* Auto-generated by scripts/embed_web.py — do not edit */
/* Source: {DIST_FILE} | raw {raw_kb:.1f} KB → gzip {comp_kb:.1f} KB */
#pragma once
#include <stddef.h>

static const unsigned char WEB_BUNDLE_GZ[] = {{
{hex_block}
}};

static const size_t WEB_BUNDLE_GZ_LEN = {len(compressed)}U;
"""

    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    with open(OUTPUT_FILE, 'w') as f:
        f.write(header)

    print(f'Written: {OUTPUT_FILE}  ({len(compressed)} bytes)')


if __name__ == '__main__':
    main()
